package services.book.data;
// Generated Oct 28, 2015 11:29:04 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Collection;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "Location")
public class Location implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "Location", nullable = false, length = 100)
	private String location;
	
	
	@Column(name = "Institution", nullable = false, length = 100)
	private String institution;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Location_Major", joinColumns = {
			@JoinColumn(name = "ID_Location", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_Major", nullable = false, updatable = false) })
	private Collection<Major> majors;

	public Location() {
	}

	public Location(String location, String institution) {
		this.location = location;
		this.institution = institution;
	}

	public Location(String location, String institution, Collection<Major> majors) {
		this.location = location;
		this.institution = institution;
		this.majors = majors;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}


	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	public Collection<Major> getMajors() {
		return majors;
	}

	public void setMajors(Collection<Major> majors) {
		this.majors = majors;
	}
	
	


}
