package services.book.data;
// Generated Oct 28, 2015 11:29:04 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Collection;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "Major")
public class Major implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "Name", nullable = false, length = 100)
	private String name;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Location_Major", joinColumns = {
			@JoinColumn(name = "ID_Major", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_Location", nullable = false, updatable = false) })
	private Collection<Location> locations;

	public Major() {
	}

	public Major(String name) {
		this.name = name;
	}

	public Major(String name, Set locations) {
		this.name = name;
		this.locations = locations;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Collection<Location> getLocations() {
		return locations;
	}

	public void setLocations(Collection<Location> locations) {
		this.locations = locations;
	}




}
