package services.book.data;
// Generated Oct 28, 2015 11:29:04 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Collection;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SellOption generated by hbm2java
 */
@Entity
@Table(name = "SellOption")
public class SellOption implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "Name", nullable = false, length = 200)
	private String name;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sellOption")
	private Collection<Book> books;

	public SellOption() {
	}

	public SellOption(String name) {
		this.name = name;
	}

	public SellOption(String name, Set books) {
		this.name = name;
		this.books = books;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Collection<Book> getBooks() {
		return books;
	}

	public void setBooks(Collection<Book> books) {
		this.books = books;
	}

		

}
