package ch.adriankrebs.services.book.data;
// Generated Oct 28, 2015 11:29:04 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import java.util.stream.Collectors;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Condition generated by hbm2java
 */
@Entity
@Table(name = "Condition")
public class Condition implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@Column(name = "name")
	private String name;

	@OneToMany(fetch = FetchType.LAZY)
	private Collection<Book> books;

	public Condition() {
	}

	public Condition(String name, Collection books) {
		this.name = name;
		this.books = books;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
	}

	public Map<String, List<String>> getByGenreAndByAuthor() {
		//return books.stream().collect(Collectors.groupingBy(Book::getName,Collectors.groupingBy(b -> String.valueOf(b.getIsbn()))));
		Consumer<Book> increasePrice = s->s.setPrice(new Double(200));
		Consumer<Book> print = System.out::println;
		books.forEach(increasePrice);
		books.stream().forEach(print);
		return books.stream().collect(Collectors.groupingBy(Book::getName,Collectors.mapping(b -> String.valueOf(b.getIsbn()), Collectors.toList())));
	}

	public Collection<Book> getBooks() {
		return books;
	}

	public void setBooks(Collection<Book> books) {
		this.books = books;
	}

}
